spring.datasource.url=jdbc:postgresql://localhost:5433/carshop
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

server.port=8080
